# Generated by Django 3.1.7 on 2021-03-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionset',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='collection_sets', to='items.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='items.Tag'),
        ),
    ]
